name: Build

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    # Disabled until we have proper tokens for testing against staging.
    #- name: Test
    #  run: go test -v ./...
